# ~/.zshrc

export ZSH="/usr/local/etc/oh-my-zsh"
export ZSH_CUSTOM="${HOME}/.config/oh-my-zsh"
ZSH_THEME="my"
export GPG_TTY=$(tty)

export PATH="${HOME}/bin:${HOME}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export LANG=en_US.UTF-8
export EDITOR='vim'

DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git wd jsontools)

source $ZSH/oh-my-zsh.sh