---
- name: >
    service/prometheus
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ mosquitto_service_user }}"


- name: >
    locals
    : Local variable structures
  set_fact:

    _mosquitto_svc_user: "{{ _user }}"

    _mosquitto_svc:
      name: mosquitto
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - data
        - log
      role: service/mosquitto
      config_templates:
        - mosquitto.conf
      description: Mosquitto MQTT
      keep_uid: True
      #network: host
      ports:
        - host_port: "{{ mosquitto_port }}"
          container_port: 1883
      volumes:
        - host_path: "{{ _user.home }}/mosquitto.conf"
          container_path: /mosquitto/config/mosquitto.conf
          options: ro,z
        - host_path: "{{ _user.home }}/data"
          container_path: /mosquitto/data
          options: z
        - host_path: "{{ _user.home }}/log"
          container_path: /mosquitto/log
          options: z
      image: docker.io/eclipse-mosquitto:latest


    _mosquitto_exporter_svc:
      name: mosquitto-exporter
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      description: Prometheus Exporter for Mosquitto MQTT
      network: host
      ports:
        - host_port: "{{ mosquitto_exporter_port }}"
          container_port: 9234
      image: docker.io/parrazam/mosquitto-exporter:latest
      container_args: >
        --endpoint
        tcp://{{
          ansible_default_ipv4.address
        }}:{{
          mosquitto_port
        }}
