---
- name: >
    service/prometheus
    : locals
    : Fill out user variables
  include_role:
    name: utils/podman/rootless/user
    tasks_from: locals
  vars:
    USER: "{{ prometheus_service_user }}"


- name: >
    locals
    : Service parameters
  set_fact:

    _prom_svc_user: "{{ _user }}"

    _prom_svc:
      name: prometheus
      user: "{{ _user.name }}"
      home: "{{ _user.home }}"
      subdirs:
        - data
      role: service/prometheus
      config_templates:
        - prometheus.yml
      description: Prometheus Monitoring
      keep_uid: True
      #network: host
      ports:
        - host_port: "{{ prometheus_port }}"
          container_port: "{{ prometheus_port }}"
      volumes:
        - host_path: "{{ _user.home }}/prometheus.yml"
          container_path: /etc/prometheus/prometheus.yml
          options: ro,z
        - host_path: "{{ _user.home }}/data"
          container_path: /prometheus
          options: z
      image: docker.io/prom/prometheus:latest
      container_args: >
        --config.file=/etc/prometheus/prometheus.yml
