FROM alpine:latest

RUN apk add --no-cache openssh;\
    ssh-keygen -t rsa -b 4096 \
        -f /etc/ssh/ssh_host_rsa_key -N "";\
    chmod 600 "/etc/ssh/ssh_host_rsa_key";

# for ALGORITHM in rsa dsa ecdsa ed25519; do
#     ssh-keygen -b 4096 \
#         -f "/etc/ssh/ssh_host_${ALGORITHM}_key" \
#         -t "${ALGORITHM}" -N ""
#     chmod 600 "/etc/ssh/ssh_host_${ALGORITHM}_key"
# done






COPY container-entrypoint.sh /container-entrypoint.sh

VOLUME /etc/ssh/sshd_config
VOLUME /etc/ssh/authorized_keys

ENTRYPOINT ["/container-entrypoint.sh"]
