---
- name: >
    shell/user
    : create : {{ _user.name }}
    : Configure for sshd login
  include_role:
    name: service/sshd/user
  when: _user.authorized_key_names

- name: >
    create : {{ _user.name }}
    : ZSH installed
  include_role:
    name: shell/zsh
  when: _user.shell == "/usr/bin/zsh"


- name: >
    create : {{ _user.name }}
    : Base user
  include_role:
    name: base/user
    tasks_from: create


- name: >
    create : {{ _user.name }}
    : SSH client
  include_role:
    name: shell/ssh/user


- name: >
    create : {{ _user.name }}
    : ZSH user setup
  include_role:
    name: shell/zsh/user
  when: _user.shell == "/usr/bin/zsh"
